export const SITE_URL = "https://bitsolmarketing.com";
export const SITE_NAME = "BITSOL Marketing";

/** Default social preview image, generated by app/opengraph-image.tsx. */
export const DEFAULT_OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "BITSOL Marketing — Digital Marketing Agency in Pakistan",
};

/**
 * Shortens text for a meta description so search results don't cut it
 * mid-word. Breaks at the last word boundary and adds an ellipsis.
 */
export function clampDescription(text: string, max = 155): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  const base = lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${base.replace(/[\s,;:.—–-]+$/, "")}…`;
}
